site:
  title: KAHU Radar Hub
  url:  https://nowhere.net
  start_page: crowdsource:ROOT:index.adoc

content:
  sources:
    - url: ..
      start_path: manual
      branches: HEAD
      edit_url: https://github.com/opencpn-manuals/crowdsource/edit/master/{path}

ui:   
  bundle:
    url: https://gitlab.com/leamas/antora-ui-default/-/raw/master/latest/ui-bundle.zip
    snapshot: true

output:
  dir: ./docs
  clean: true              
